# Avatar Framer Config
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Avatar Framer
description: >- # this means to ignore newlines"
  Một công cụ đơn giản để tạo ảnh đại diện có khung cho mạng xã hội nhằm ủng hộ một mục đích nào đó.
  Tự động tạo một trang web tĩnh dựa trên số lượng hình ảnh khung được cung cấp.

# Copy
# Fill in your copy for the title and steps here
# 
title-text: " "
step-1: "Tải lên bức ảnh mà bạn muốn thay đổi."
step-2: "Sử dụng các công cụ Rotation để xoay hình ảnh, Scale để phóng to thu nhỏ ảnh. Bạn có thể di chuyển hình ảnh của bạn trên phần xem trước."
step-3: "Chọn khung hình của bạn."
step-4: "Tải xuống hình ảnh đại diện mới của bạn!"
# step-5: "Đăng trên mạng xã hội với hashtag #TeamBartlet."
footer-text: "© 2024 AI Robotic, Inc. All rights reserved."

# Header Nav Link
#
# nav-link: "http://google.com"
# nav-link-text: "Donate"

# Buttons and upload form
# 
upload-text: "Kéo thả hình ảnh vào đây hoặc click vào để tải lên hình ảnh."
download-button-text: "Tải về hình ảnh của bạn"

# Logo & Favicon
# 
logo: "logo.png"
favicon: "favicon.ico"

# Footer links
# 
# footer-links:
#   - text: "Awesome page 1"
#     link: "http://google.com"

#   - text: "Other page 2"
#     link: "http://google.com"

#   - text: "Things!"
#     link: "http://google.com"

# Open Graph and Twitter Cards
#
# og-title: Create your own avatar generating website
# og-description: Create your own avatar generating website
# og-url: https://andrewquinn.ca/avatar-framer
# og-image: "og-image.png"
# og-image-width: 1280
# og-image-height: 640
# twitter-card: summary_large_image
# twitter-description: Create your own avatar generating website
# twitter-image: "og-image.png"
# twitter-handle: "@AndrewQuinn2"

keep_files:
  - dist/js/bundle.js

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# 
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - "*.config.js"
  - "*.config.json"
  - "package*.json"
  - README.md
